### PR TITLE
Add `--verbose` flag v 3.0

### LINKED ISSUE #38: show more details in results
It would be handy if the results showed more details (similar to the fast.com website) such as the latency stats and the server location.

### PR DESCRIPTION
**Pull request by skywinder**
Resolves #38 (and will close #40 and ~~updates~~ close #41).

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hey, sorry for the slow reply. I completely missed this pull request...

Are you still interested in finishing it? I totally understand if not.

**Comment by skywinder** [comment]
@sindresorhus hi, let's finish it.  is there anything to be done?

**Comment by sindresorhus** [comment]
Sure. You need to resolve the merge conflict and ensure the changes still work.

**Comment by sindresorhus** [comment]
Bump :)

**Pull request closed without merging**
